mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.zzy.pojo

server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/restful?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    #timeout: 0
    #cluster:
      # redis最大重连数
      #max-redirects: 3
      #nodes: 127.0.0.1:6379
    jedis:
      pool:
        # 最大空闲数
        max-idle: 5
        # 最小空闲数
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1



